<?php

namespace Necowebs\Destiny\Services\Manifest;

use Collections\Collection;
use Necowebs\Destiny\Exceptions\ManifestObjectNotFoundException;
use Necowebs\Destiny\Models\Manifest\SandboxPerkGroup;
use Necowebs\Destiny\Models\Manifest\TalentGrid;
use Necowebs\Destiny\Models\Manifest\TalentGridActivationRequirement;
use Necowebs\Destiny\Models\Manifest\TalentGridExclusiveSet;
use Necowebs\Destiny\Models\Manifest\TalentGridNode;
use Necowebs\Destiny\Models\Manifest\TalentGridStep;

/**
 * Class TalentGridServiceTest
 * @package Necowebs\Destiny\Services\Manifest
 */
class TalentGridServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Test Get Talent Grid
     */
    public function testGetTalentGrid()
    {
        $grid = (new TalentGridService())->getTalentGrid(148625784);

        $expected = (new TalentGrid())
            ->setGridHash(148625784)
            ->setMaxGridLevel(0)
            ->setGridLevelPerColumn(0)
            ->setProgressionHash(3605101483)
            ->setNodes(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridNode', [
                (new TalentGridNode())
                    ->setNodeIndex(0)
                    ->setNodeHash(0)
                    ->setRow(0)
                    ->setColumn(0)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(true)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(2688431654)
                            ->setNodeStepName('Arc Damage')
                            ->setNodeStepDescription('This weapon causes Arc Damage.')
                            ->setInteractionDescription('Reroll')
                            ->setIcon('/common/destiny_content/icons/d4ba42b52bf9bc3edf180a20616a81b1.png')
                            ->setDamageType(2)
                            ->setDamageTypeHash(2303181850)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(0)
                                ->setMaterialRequirementHashes(new Collection('int'))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int', [839929915]))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(0)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(2)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int'))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(1)
                    ->setNodeHash(1)
                    ->setRow(0)
                    ->setColumn(2)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(3528431156)
                            ->setNodeStepName('Hidden Hand')
                            ->setNodeStepDescription('This weapon gains better target acquisition.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/15b516f1995f38de050e20b234c7b8c0.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(3)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int', [2507926095]))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int'))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(2)
                    ->setNodeHash(2)
                    ->setRow(0)
                    ->setColumn(4)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(true)
                    ->setRandomActivationRequirement((new TalentGridActivationRequirement())
                        ->setGridLevel(0)
                    )
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(1450441122)
                            ->setNodeStepName('Demotion')
                            ->setNodeStepDescription('This weapon has a chance to stun Fallen Captains.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/5f96b2d9ceda125dd79866f430f6d621.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [2439761463]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false),
                        (new TalentGridStep())
                            ->setStepIndex(1)
                            ->setNodeStepHash(3985040583)
                            ->setNodeStepName('Disciplinarian')
                            ->setNodeStepDescription('This weapon deals a small amount of bonus damage to Fallen enemies.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/c98f3fcb82c3dd2053ddb9bf6a72e32a.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [1797364692]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false),
                        (new TalentGridStep())
                            ->setStepIndex(2)
                            ->setNodeStepHash(300289986)
                            ->setNodeStepName('Dreg Burn')
                            ->setNodeStepDescription('This weapon deals moderate bonus damage to Fallen Dregs.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/50230c265ee5e6d810507bbf008f6e74.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [750820802]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false),
                        (new TalentGridStep())
                            ->setStepIndex(3)
                            ->setNodeStepHash(1782221257)
                            ->setNodeStepName('Shank Burn')
                            ->setNodeStepDescription('This weapon deals moderate bonus damage to Fallen Shanks.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/50230c265ee5e6d810507bbf008f6e74.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [2066029413]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false),
                        (new TalentGridStep())
                            ->setStepIndex(4)
                            ->setNodeStepHash(431265444)
                            ->setNodeStepName('Mutineer')
                            ->setNodeStepDescription('This weapon has a chance of suppressing a Fallen Captain\'s abilities.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/86995c376e1ec6202e5128da630ed336.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [975069794]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false),
                        (new TalentGridStep())
                            ->setStepIndex(5)
                            ->setNodeStepHash(3707521590)
                            ->setNodeStepName('Vandal Burn')
                            ->setNodeStepDescription('This weapon deals moderate bonus damage to Fallen Vandals.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/50230c265ee5e6d810507bbf008f6e74.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(true)
                            ->setPerkHashes(new Collection('int', [3533846394]))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(false)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int'))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(3)
                    ->setNodeHash(3)
                    ->setRow(2)
                    ->setColumn(1)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(4017426047)
                            ->setNodeStepName('Red Dot-ORES')
                            ->setNodeStepDescription("Flexible sight. \nEnhances handling, range, and recoil control.")
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/2222e2fe270aef863ce4909ebf776dfa.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(3)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int', [1240592695, 155624089, 4188031367, 943549884, 3291498656]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(232)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [4, 5]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(4)
                    ->setNodeHash(4)
                    ->setRow(1)
                    ->setColumn(1)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(3975020101)
                            ->setNodeStepName('Red Dot-OES')
                            ->setNodeStepDescription("Agile sight. \nFor smooth engagement in close quarters.")
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/2222e2fe270aef863ce4909ebf776dfa.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(2)
                                ->setMaterialRequirementHashes(new Collection('int'))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int', [1240592695, 155624089, 3291498656]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(40)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [3, 5]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(5)
                    ->setNodeHash(5)
                    ->setRow(0)
                    ->setColumn(1)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(true)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(792270175)
                            ->setNodeStepName('FastDraw IS')
                            ->setNodeStepDescription("Standard sight.\nA lightweight design, good for recoil control.")
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/9f3ecc2e45f3a383eb100246838a454e.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(0)
                                ->setMaterialRequirementHashes(new Collection('int'))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int', [155624089, 4188031367, 943549884, 3291498656]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(224)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [3, 4]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(6)
                    ->setNodeHash(6)
                    ->setRow(2)
                    ->setColumn(3)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(1670053670)
                            ->setNodeStepName('Enhanced Battery')
                            ->setNodeStepDescription('Increases magazine size.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/b40803d0c09f12e3bef4eb0da2868858.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(7)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int', [3871231066]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(512)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [7, 8]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(7)
                    ->setNodeHash(7)
                    ->setRow(0)
                    ->setColumn(3)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(3069944219)
                            ->setNodeStepName('Speed Reload')
                            ->setNodeStepDescription('Reload this weapon quickly.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/b79955b61fc3635906dce89f97534f3b.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(5)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(4398)
                            ->setStatHashes(new Collection('int', [4188031367]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(128)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [6, 8]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(8)
                    ->setNodeHash(8)
                    ->setRow(1)
                    ->setColumn(3)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(false)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(3661313476)
                            ->setNodeStepName('Accelerated Coils')
                            ->setNodeStepDescription('Reduces weapon charge time in exchange for slightly decreased damage.')
                            ->setInteractionDescription('Upgrade')
                            ->setIcon('/common/destiny_content/icons/02fa24ad39416a727b53f00c64d73d6e.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(6)
                                ->setMaterialRequirementHashes(new Collection('int', [2627491173, 2627491172, 2627491175, 2627491174]))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(9196)
                            ->setStatHashes(new Collection('int', [2961396640]))
                            ->setAffectsQuality(false)
                            ->setStepGroups((new SandboxPerkGroup())
                                ->setWeaponPerformance(4096)
                                ->setImpactEffects(0)
                                ->setGuardianAttributes(0)
                                ->setLightAbilities(0)
                                ->setDamageTypes(0)
                            )
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int', [6, 7]))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
                (new TalentGridNode())
                    ->setNodeIndex(9)
                    ->setNodeHash(9)
                    ->setRow(0)
                    ->setColumn(-1)
                    ->setPrerequisiteNodeIndexes(new Collection('int'))
                    ->setBinaryPairNodeIndex(-1)
                    ->setAutoUnlocks(true)
                    ->setLastStepRepeats(false)
                    ->setIsRandom(false)
                    ->setIsRandomRepurchasable(false)
                    ->setSteps(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridStep', [
                        (new TalentGridStep())
                            ->setStepIndex(0)
                            ->setNodeStepHash(0)
                            ->setIcon('/img/misc/missing_icon.png')
                            ->setDamageType(0)
                            ->setDamageTypeHash(0)
                            ->setActivationRequirement((new TalentGridActivationRequirement())
                                ->setGridLevel(0)
                                ->setMaterialRequirementHashes(new Collection('int', []))
                            )
                            ->setCanActivateNextStep(false)
                            ->setNextStepIndex(-1)
                            ->setIsNextStepRandom(false)
                            ->setPerkHashes(new Collection('int'))
                            ->setStartProgressionBarAtProgress(0)
                            ->setStatHashes(new Collection('int'))
                            ->setAffectsQuality(true)
                            ->setTrueStepIndex(0)
                            ->setTruePropertyIndex(0)
                            ->setAffectsLevel(false)
                    ]))
                    ->setExlusiveWithNodes(new Collection('int'))
                    ->setRandomStartProgressionBarAtProgression(0)
                    ->setOriginalNodeHash(0),
            ]))
            ->setCalcMaxGridLevel(0)
            ->setCalcProgressToMaxLevel(0)
            ->setExclusiveSets(new Collection('Necowebs\Destiny\Models\Manifest\TalentGridExclusiveSet', [
                (new TalentGridExclusiveSet())->setNodeIndexes(new Collection('int', [3, 4, 5])),
                (new TalentGridExclusiveSet())->setNodeIndexes(new Collection('int', [6, 7, 8]))
            ]))
            ->setIndependentNodeIndexes(new Collection('int', [1, 2]))
            ->setHash(148625784)
            ->setIndex(0);

        $this->assertEquals($expected, $grid);
    }

    /**
     * Test Get Talent Grid Exception
     */
    public function testGetTalentGridException()
    {
        $this->expectException(ManifestObjectNotFoundException::class);

        $grid = (new TalentGridService())->getTalentGrid('Fail');
    }
}
