<?php

namespace Necowebs\Destiny\Services\Manifest;

use Collections\Collection;
use Necowebs\Destiny\Exceptions\ManifestObjectNotFoundException;
use Necowebs\Destiny\Models\Manifest\Vendor;
use Necowebs\Destiny\Models\Manifest\VendorSummary;
use Necowebs\Destiny\Models\Manifest\VendorCategory;

/**
 * Class VendorServiceTest
 * @package Necowebs\Destiny\Services\Manifest
 */
class VendorServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Test Get Vendor
     */
    public function testGetVendor()
    {
        $vendor = (new VendorService())->getVendor(1575820975);

        $expected = (new Vendor())
            ->setSummary((new VendorSummary())
                ->setVendorHash(1575820975)
                ->setVendorName('Warlock Vanguard')
                ->setVendorDescription('Respected among all Orders, Ikora Rey tutors new Warlocks with a lifetime of hard-earned knowledge.')
                ->setVendorIcon('/common/destiny_content/icons/627c0986dd67898d292e9da6414d6d2e.png')
                ->setVendorOrder(90)
                ->setFactionName('Vanguard Reputation')
                ->setFactionIcon('/common/destiny_content/icons/be454db6edaa4900c9f154909a2fd174.png')
                ->setFactionHash(468098704)
                ->setFactionDescription("Complete Vanguard Bounties to unlock powerful gear for purchase.\n\nAchieve high Rank to earn rewards.")
                ->setResetIntervalMinutes(180)
                ->setResetOffsetMinutes(32640)
                ->setVendorIdentifier('VENDOR_WARLOCK_MENTOR')
                ->setPositionX(1116)
                ->setPositionY(367)
                ->setTransitionNodeIdentifier('TOWER_NODE')
                ->setVisible(true)
                ->setProgressionHash(3233510749)
                ->setSellString('Acquire')
                ->setBuyString('Acquire')
                ->setVendorPortrait('/img/destiny_content/vendor/bbffb19be8ea4c18b2d5e68a4ba305bc.png')
                ->setVendorBanner('/img/destiny_content/vendor/VendorBanner.png')
                ->setUnlockFlagHashes(new Collection('int'))
                ->setEnabledUnlockFlagHashes(new Collection('int', [2678892537]))
                ->setMapSectionIdentifier('VANGUARD')
                ->setMapSectionName('Vanguard')
                ->setMapSectionOrder(2)
                ->setShowOnMap(true)
                ->setEventHash(0)
                ->setVendorCategoryHash(2)
                ->setVendorCategoryHashes(new Collection('int', [2]))
                ->setVendorSubcategoryHash(300)
                ->setInhibitBuying(false)
            )
            ->setAcceptedItems(new Collection('int'))
            ->setCategories(new Collection('Necowebs\Destiny\Models\Manifest\VendorCategory', [
                (new VendorCategory())
                    ->setCategoryHash(3788886265)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(4187908026)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Select')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('Your renown grows. The city factions have been asking for you by name.')
                    ->setOverlayChoice('Select a reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                ->setCategoryHash(3788886266)
                ->setDisplayTitle('Factions of the City')
                ->setOverlayCurrencyItemHash(4187908025)
                ->setQuantityAvailable(0)
                ->setShowUnavailableItems(false)
                ->setHideIfNoCurrency(true)
                ->setBuyStringOverride('Accept')
                ->setOverlayTitle('Factions of the City')
                ->setOverlayDescription('You met the full force of the Vex - and you turned them back. Incredible.')
                ->setOverlayChoice('Accept gift:')
                ->setOverlayIcon('/img/misc/missing_icon.png')
                ->setHasOverlay(true)
                ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(963294657)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(100134273)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Select')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('Using Golden Age labs to understand the Vex? You and your Ghost make a resourceful team.')
                    ->setOverlayChoice('Select a reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(963294658)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(100134274)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Select')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('Venus is a test that many Guardians fail.')
                    ->setOverlayChoice('Select a reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(3414827909)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(3813849669)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Accept')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('You will be remembered forever as the Shrinebreaker, bane of the Hive.')
                    ->setOverlayChoice('Accept reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(3414827911)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(3813849671)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Select')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('The Sword of Crota is broken! You have avenged so many lost.')
                    ->setOverlayChoice('Select a reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(2784353176)
                    ->setDisplayTitle('Mission Reward')
                    ->setOverlayCurrencyItemHash(1455055448)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setBuyStringOverride('Select')
                    ->setOverlayTitle('Mission Reward')
                    ->setOverlayDescription('The Hive threat must be answered.')
                    ->setOverlayChoice('Select a reward:')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(3762955427)
                    ->setDisplayTitle('Welcome, Guardian')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setBuyStringOverride('Accept')
                    ->setOverlayTitle('Welcome, Guardian')
                    ->setOverlayChoice('Welcome to the fight.')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(true)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(1265092242)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(6)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(1274679658)
                    ->setDisplayTitle('Vanguard Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(12)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(2926085347)
                    ->setDisplayTitle('Vanguard Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(12)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(3491260420)
                    ->setDisplayTitle('Vanguard Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(12)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(4250336072)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(4250336074)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(4250336068)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(485333511)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(485333509)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(485333507)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(485333505)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(485333519)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(502111226)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(4286415917)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(2887135587)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(20)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(3550963174)
                    ->setDisplayTitle('Rewards')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(4053330898)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(716915525)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(716915520)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(666582668)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(683360383)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(633027494)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(2375687066)
                    ->setDisplayTitle('Rewards')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(1061012828)
                    ->setDisplayTitle('Rewards')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(1456560444)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(1456560445)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(1456560446)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(664980845)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(437748860)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(3788370342)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(1854066485)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(589736698)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(true)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(3234039927)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(647681844)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(3893443410)
                    ->setDisplayTitle('')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true),
                (new VendorCategory())
                    ->setCategoryHash(502111224)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(502111230)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(502111228)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(502111218)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(518888813)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(518888815)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(518888809)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(518888811)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(518888805)
                    ->setDisplayTitle('Warlock Armor')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(2)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(2113006028)
                    ->setDisplayTitle('Rank 1')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(10)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(2113006031)
                    ->setDisplayTitle('Rank 2')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(10)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(2113006030)
                    ->setDisplayTitle('Rank 3')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(10)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(false),
                (new VendorCategory())
                    ->setCategoryHash(1760130521)
                    ->setDisplayTitle('Rewards')
                    ->setOverlayCurrencyItemHash(0)
                    ->setQuantityAvailable(0)
                    ->setShowUnavailableItems(false)
                    ->setHideIfNoCurrency(false)
                    ->setOverlayTitle('')
                    ->setOverlayDescription('')
                    ->setOverlayChoice('')
                    ->setOverlayIcon('/img/misc/missing_icon.png')
                    ->setHasOverlay(false)
                    ->setHideFromRegularPurchase(true)
            ]))
            ->setFailureStrings([null])
            ->setUnlockValueHash(0)
            ->setHash(1575820975)
            ->setIndex(0);

        $this->assertEquals($expected, $vendor);
    }

    /**
     * Test Get Vendor Exception
     */
    public function testGetVendorException()
    {
        $this->expectException(ManifestObjectNotFoundException::class);

        $vendor = (new VendorService())->getVendor('Fail');
    }
}
